apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mszj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mszj
    app.kubernetes.io/part-of: tkwch-fix-0075-0027-app
  name: devfile-sample-mszj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mszj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mszj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0027-tenant/tkwch-fix-0075-0027-app/devfile-sample-mszj@sha256:9e21ae97b823a5454eadf4bb53604fc5cf8cdb945e1523484852eb45e59ee82a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
